---
openapi: 3.0.1
info:
  title: DataBridge Order Service API
  version: v1
  description: API for managing customer orders, order items, and order status tracking
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
paths:
  "/api/v1/orders":
    get:
      summary: Lists all orders
      tags:
      - Orders
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      - name: status
        in: query
        required: false
        description: Filter by status
        schema:
          type: string
      - name: customer_id
        in: query
        required: false
        description: Filter by customer
        schema:
          type: integer
      - name: start_date
        in: query
        format: date
        required: false
        description: Filter by start date
        schema:
          type: string
      - name: end_date
        in: query
        format: date
        required: false
        description: Filter by end date
        schema:
          type: string
      - name: sort_by
        in: query
        required: false
        description: Field to sort by
        schema:
          type: string
      - name: sort_direction
        in: query
        required: false
        description: Sort direction (asc or desc)
        schema:
          type: string
      security:
      - bearer_auth: []
      responses:
        '200':
          description: orders found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    customer_id:
                      type: integer
                    status:
                      type: string
                    total_amount:
                      type: number
                      format: float
                    notes:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
    post:
      summary: Creates an order
      tags:
      - Orders
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: order created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer_id:
                    type: integer
                  status:
                    type: string
                  total_amount:
                    type: number
                    format: float
                  notes:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                line_items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                      unit_price:
                        type: number
                        format: float
                    required:
                    - product_id
                    - quantity
                    - unit_price
              required:
              - customer_id
              - line_items
  "/api/v1/orders/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves an order
      tags:
      - Orders
      security:
      - bearer_auth: []
      responses:
        '200':
          description: order found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer_id:
                    type: integer
                  status:
                    type: string
                  total_amount:
                    type: number
                    format: float
                  notes:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  line_items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        order_id:
                          type: integer
                        product_id:
                          type: integer
                        quantity:
                          type: integer
                        unit_price:
                          type: number
                          format: float
                        total_price:
                          type: number
                          format: float
                  payments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        order_id:
                          type: integer
                        amount:
                          type: number
                          format: float
                        payment_method:
                          type: string
                        status:
                          type: string
                        transaction_id:
                          type: string
                          nullable: true
                  shipments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        order_id:
                          type: integer
                        tracking_number:
                          type: string
                          nullable: true
                        carrier:
                          type: string
                          nullable: true
                        status:
                          type: string
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Updates an order
      tags:
      - Orders
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: order updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer_id:
                    type: integer
                  status:
                    type: string
                  total_amount:
                    type: number
                    format: float
                  notes:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                  - created
                  - processing
                  - fulfilled
                  - canceled
    delete:
      summary: Cancels an order
      tags:
      - Orders
      security:
      - bearer_auth: []
      responses:
        '204':
          description: order canceled
        '404':
          description: order not found
  "/api/v1/orders/{order_id}/payments":
    parameters:
    - name: order_id
      in: path
      description: Order ID
      required: true
      schema:
        type: integer
    get:
      summary: Lists all payments for an order
      tags:
      - Payments
      security:
      - bearer_auth: []
      responses:
        '200':
          description: payments found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    order_id:
                      type: integer
                    amount:
                      type: number
                      format: float
                    payment_method:
                      type: string
                    status:
                      type: string
                    transaction_id:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Creates a payment for an order
      tags:
      - Payments
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: payment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  order_id:
                    type: integer
                  amount:
                    type: number
                    format: float
                  payment_method:
                    type: string
                  status:
                    type: string
                  transaction_id:
                    type: string
                    nullable: true
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                payment_method:
                  type: string
                  enum:
                  - credit_card
                  - paypal
                  - bank_transfer
                status:
                  type: string
                  enum:
                  - pending
                  - completed
                  - failed
                transaction_id:
                  type: string
                  nullable: true
              required:
              - amount
              - payment_method
  "/api/v1/orders/{order_id}/shipments":
    parameters:
    - name: order_id
      in: path
      description: Order ID
      required: true
      schema:
        type: integer
    get:
      summary: Lists all shipments for an order
      tags:
      - Shipments
      security:
      - bearer_auth: []
      responses:
        '200':
          description: shipments found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    order_id:
                      type: integer
                    tracking_number:
                      type: string
                      nullable: true
                    carrier:
                      type: string
                      nullable: true
                    status:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Creates a shipment for an order
      tags:
      - Shipments
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: shipment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  order_id:
                    type: integer
                  tracking_number:
                    type: string
                    nullable: true
                  carrier:
                    type: string
                    nullable: true
                  status:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '404':
          description: order not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tracking_number:
                  type: string
                carrier:
                  type: string
                status:
                  type: string
                  enum:
                  - pending
                  - shipped
                  - delivered
                  - returned
  "/api/v1/orders/{order_id}/shipments/{id}":
    parameters:
    - name: order_id
      in: path
      description: Order ID
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: Shipment ID
      required: true
      schema:
        type: integer
    put:
      summary: Updates a shipment
      tags:
      - Shipments
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: shipment updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  order_id:
                    type: integer
                  tracking_number:
                    type: string
                    nullable: true
                  carrier:
                    type: string
                    nullable: true
                  status:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: shipment not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tracking_number:
                  type: string
                carrier:
                  type: string
                status:
                  type: string
                  enum:
                  - pending
                  - shipped
                  - delivered
                  - returned
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3003
